<?php
use Drupal\Core\Database\Database;

require_once("lib/grid.php");
global $grid_lib;
$grid_lib=new grid_library();

//TODO load drupal specific classes
//TODO provide CKEDITOR Config
//TODO provide default css via menu hook to frontend
//TODO grid admin settings overview page and menu entry
//TODO container factory
//TODO file upload hook
//TODO reusable boxes page
//TODO reusable containers
//TODO grid styles

/**
 * Created by PhpStorm.
 * User: enno
 * Date: 14.08.15
 * Time: 16:15
 */

function grid_get_storage()
{

    //TODO: find the templates path
    //TODO: port grid_drupal_ajaxendpoint over!


    $cache=&drupal_static(__FUNCTION__);
    if(!isset($cache))
    {
        $cache=array();
    }
    if(!isset($cache['loaded']))
    {
        \Drupal::moduleHandler()->invokeAll('grid_load_classes');
        $cache['loaded']=TRUE;
    }
    if(isset($cache['storage']))
    {
        return $cache['storage'];
    }

    $conn=Database::getConnection();
    $opts=$conn->getConnectionOptions();
    global $user;
    $username="UNDEFINED";
    if(isset($user->name))
        $username=$user->name;
    $storage=new grid_db($opts['host'],$opts['username'],$opts['password'],$opts['database'],$username,$conn->tablePrefix());

    //$storage->templatesPaths=grid_get_templates_paths();

    $config=\Drupal::config("grid.settings");
    $storage->containerstyle=$config->get("default_container_style");

    if($storage->containerstyle=='__NONE__')
        $storage->containerstyle=NULL;
    $storage->slotstyle=$config->get("defualt_slot_style");
    if($storage->slotstyle=='__NONE__')
        $storage->slotstyle=NULL;
    $storage->boxstyle=$config->get("default_box_style");
    if($storage->boxstyle=='__NONE__')
        $storage->boxstyle=NULL;
    $storage->ajaxEndpoint=new grid_ajaxendpoint();//new grid_drupal_ajaxendpoint();
    $storage->ajaxEndpoint->storage=$storage;
    $cache['storage']=$storage;
    return $storage;
}

function grid_get_grid_by_nid($nodeid)
{
    $grid_id=db_select("grid_nodes")->fields("grid_nodes",array("grid_id"))->condition("nid",$nodeid)->execute()->fetchAssoc();
    if($grid_id===FALSE)
    {
        return FALSE;
    }
    else
    {
        return $grid_id['grid_id'];
    }
}

function grid_get_additional_editor_widgets(){

    $editor_widgets = array("css" => array(), "js" => array());
    \Drupal::moduleHandler()->alter('grid_editor_widgets', $editor_widgets);
    return $editor_widgets;
}

function grid_get_additional_box_editmode_css(){
    $css=\Drupal::moduleHandler()->invokeAll('grid_boxes_editmode_css');
    if(!is_array($css))
        return array();
    return $css;
}


/**
 * Implements hook_library_info_build().
 */
function grid_library_info_build()
{
    $language=\Drupal::languageManager()->getCurrentLanguage();
    global $grid_lib;

    $js=array();
    $css=array();
    /**
     * get additional field types
     */
    $editor_widgets = grid_get_additional_editor_widgets();

    /**
     * add editor js files
     */
    $jsfiles=$grid_lib->getEditorJS($language->getId(),FALSE);
    foreach($jsfiles as $idx=>$file)
    {
        $js['/'.drupal_get_path('module','grid')."/lib/".$file]=array();
    }
    foreach( $editor_widgets["js"] as $idx=>$file )
    {
        $js['/'.$file]=array();
    }

    $base=drupal_get_path('module','grid');
    $css['/'.$base."/grid-drupal.css"]=array();

    $cssfiles=$grid_lib->getEditorCSS($language->getDirection(),FALSE);
    foreach($cssfiles as $idx=>$file)
    {
        $css['/'.drupal_get_path("module","grid")."/lib/".$file]=array();
    }
    foreach($editor_widgets["css"] as $idx=>$file)
    {
        $css['/'.$file]=array();
    }
    $box_editmode_css=grid_get_additional_box_editmode_css();
    foreach($box_editmode_css as $idx=>$file)
    {
        $css['/'.$file]=array();
    }

    return array(
        'editor'=>array(
            'title'=>'Grid Editor Assets',
            'website'=>'http://www.palasthotel.de',
            'version'=>'1.0',
            'js'=>$js,
            'css'=>array('base'=>$css),
            'dependencies'=>array('core/jquery'),
        ),
    );
}